Repository 2023SVBootcamp-Team-H/backend_test, pull requests merged in 2023-07, with the labels that each got.

#1 Worry & Answer Model
  .gitignore
  TestProject/TestProject/settings.py
  TestProject/TestProject/urls.py
  TestProject/db.sqlite3
  TestProject/worry/__init__.py
  TestProject/worry/admin.py
  TestProject/worry/apps.py
  TestProject/worry/models.py
  TestProject/worry/serializer.py
  TestProject/worry/tests.py
  TestProject/worry/urls.py
  TestProject/worry/views.py
  requirements.txt
Labels: enhancement

#3 feat : 기초 CRUD & Answer model
  TestProject/TestProject/settings.py
  TestProject/TestProject/urls.py
  TestProject/answer/__init__.py
  TestProject/answer/admin.py
  TestProject/answer/apps.py
  TestProject/answer/models.py
  TestProject/answer/tests.py
  TestProject/answer/urls.py
  TestProject/answer/views.py
  TestProject/worry/models.py
  TestProject/worry/urls.py
  TestProject/worry/views.py
Labels: enhancement

#7 feat : worry post
  .gitignore
  TestProject/worry/views.py
Labels: enhancement

#12 fix : except process in worry.views 145line
  TestProject/worry/views.py
Labels: bug

#26 feat : make file about docker
  .dockerignore
  Dockerfile
  docker-compose.yml
Labels: feat

#33 feat:swagger api명세 구체화
  dontworry/answer/views.py
  dontworry/category/views.py
  dontworry/personality/views.py
  dontworry/rank/views.py
  dontworry/worry/views.py
Labels: feat

#35 feat : sse 기술을 이용해 stream 문자열 통신 가능
  dontworry/config/settings.py
  dontworry/worry/urls.py
  dontworry/worry/views.py
Labels: feat

#37 feat : Prompt 형식 적용
  dontworry/personality/models.py
  dontworry/personality/views.py
  dontworry/worry/views.py
Labels: enhancement

#39 refactor : 중간 리팩토링
  dontworry/answer/models.py
  dontworry/answer/views.py
  dontworry/category/models.py
  dontworry/category/views.py
  dontworry/config/settings.py
  dontworry/config/urls.py
  dontworry/personality/models.py
  dontworry/personality/views.py
  dontworry/user/models.py
  dontworry/worry/models.py
  dontworry/worry/urls.py
Labels: Refactor

#40 feat : GitHub Action CI/CD
  .github/workflows/Django_CD.yml
  .github/workflows/Django_CI.yml
  .github/workflows/docker-image.yml
  docker-compose.yml
  requirements.txt
Labels: enhancement

#42 refactor : CI/CD 한 파일로 관리
  .github/workflows/Django_CI.yml
  .github/workflows/Django_CICD.yml
Labels: Refactor

#44 refactor : CI/CD 코드 수정
  .github/workflows/Django_CICD.yml
Labels: Refactor

#46 feat : K6 임시 시나리오
  .gitignore
  K6_LoadTest/package.json
  K6_LoadTest/script.js
Labels: enhancement

#48 feat : AWS RDS 연동 성공
  dontworry/config/settings.py
Labels: enhancement

#50 fix : CI/CD 코드 수정
  .github/workflows/Django_CICD.yml
  docker-compose.yml
  dontworry/config/settings.py
Labels: Fix
